version: "3"
services:
  dynamo:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local-Contacts
    ports:
      - "8000:8000"
    volumes:
      - ".:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal